name: bytebank
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_database: ^12.0.1
  provider: ^6.1.5+1
  cloud_firestore: ^6.0.1
  intl: ^0.20.2
  mask_text_input_formatter: ^2.9.0
  fl_chart: ^1.1.1
  characters: ^1.4.0
  vector_math: ^2.2.0
  firebase_storage: ^13.0.2
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  flutter_slidable: ^4.0.1
  uuid: ^4.5.1
  google_fonts: ^6.1.0
  riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
