// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8uRK9e-VAPZatJeWIIYaUPHxCWAwMP9o',
    appId: '1:896567907440:web:e4d451aea9c13cd1bc10b5',
    messagingSenderId: '896567907440',
    projectId: 'fiap---bytebank',
    authDomain: 'fiap---bytebank.firebaseapp.com',
    databaseURL: 'https://fiap---bytebank-default-rtdb.firebaseio.com',
    storageBucket: 'fiap---bytebank.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzelNMzdiMkfwJUjFUevZDFXa7OP3_UhY',
    appId: '1:896567907440:android:d0c94284ed802a39bc10b5',
    messagingSenderId: '896567907440',
    projectId: 'fiap---bytebank',
    databaseURL: 'https://fiap---bytebank-default-rtdb.firebaseio.com',
    storageBucket: 'fiap---bytebank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP5IkXzCC_gzBIZmG4QKLP0uS90anUm3Y',
    appId: '1:896567907440:ios:575d5e4dc67e9f08bc10b5',
    messagingSenderId: '896567907440',
    projectId: 'fiap---bytebank',
    databaseURL: 'https://fiap---bytebank-default-rtdb.firebaseio.com',
    storageBucket: 'fiap---bytebank.firebasestorage.app',
    iosBundleId: 'com.example.bytebank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP5IkXzCC_gzBIZmG4QKLP0uS90anUm3Y',
    appId: '1:896567907440:ios:575d5e4dc67e9f08bc10b5',
    messagingSenderId: '896567907440',
    projectId: 'fiap---bytebank',
    databaseURL: 'https://fiap---bytebank-default-rtdb.firebaseio.com',
    storageBucket: 'fiap---bytebank.firebasestorage.app',
    iosBundleId: 'com.example.bytebank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8uRK9e-VAPZatJeWIIYaUPHxCWAwMP9o',
    appId: '1:896567907440:web:f8ff24239551716cbc10b5',
    messagingSenderId: '896567907440',
    projectId: 'fiap---bytebank',
    authDomain: 'fiap---bytebank.firebaseapp.com',
    databaseURL: 'https://fiap---bytebank-default-rtdb.firebaseio.com',
    storageBucket: 'fiap---bytebank.firebasestorage.app',
  );
}
